"kind/bug":
  - '^[Ff]ix(\(.*\))?:?.*'
"kind/cleanup":
  - '^[Cc]hore(\(.*\))?:?.*'
"documentation":
  - '^[Dd]ocs?(\(.*\))?:?.*'
"kind/feature":
  - '^[Rr]efactor(\(.*\))?:?.*'
  - '^[Ff]eat(\(.*\))?:?.*'
