/*
 *
 *  * Copyright 2021 KubeClipper Authors.
 *  *
 *  * Licensed under the Apache License, Version 2.0 (the "License");
 *  * you may not use this file except in compliance with the License.
 *  * You may obtain a copy of the License at
 *  *
 *  *     http://www.apache.org/licenses/LICENSE-2.0
 *  *
 *  * Unless required by applicable law or agreed to in writing, software
 *  * distributed under the License is distributed on an "AS IS" BASIS,
 *  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  * See the License for the specific language governing permissions and
 *  * limitations under the License.
 *
 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubeclipper/kubeclipper/pkg/scheme/operations/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOperations implements OperationInterface
type FakeOperations struct {
	Fake *FakeOperationsV1alpha1
}

var operationsResource = schema.GroupVersionResource{Group: "operations.kubeclipper.io", Version: "v1alpha1", Resource: "operations"}

var operationsKind = schema.GroupVersionKind{Group: "operations.kubeclipper.io", Version: "v1alpha1", Kind: "Operation"}

// Get takes name of the operation, and returns the corresponding operation object, and an error if there is any.
func (c *FakeOperations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Operation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(operationsResource, name), &v1alpha1.Operation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Operation), err
}

// List takes label and field selectors, and returns the list of Operations that match those selectors.
func (c *FakeOperations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.OperationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(operationsResource, operationsKind, opts), &v1alpha1.OperationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.OperationList{ListMeta: obj.(*v1alpha1.OperationList).ListMeta}
	for _, item := range obj.(*v1alpha1.OperationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested operations.
func (c *FakeOperations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(operationsResource, opts))
}

// Create takes the representation of a operation and creates it.  Returns the server's representation of the operation, and an error, if there is any.
func (c *FakeOperations) Create(ctx context.Context, operation *v1alpha1.Operation, opts v1.CreateOptions) (result *v1alpha1.Operation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(operationsResource, operation), &v1alpha1.Operation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Operation), err
}

func (c *FakeOperations) Cancel(ctx context.Context, name string, request *v1alpha1.OperationControlRequest) (result *v1alpha1.Operation, err error) {
	body := &v1alpha1.Operation{ObjectMeta: v1.ObjectMeta{Name: name, UID: request.UID, ResourceVersion: request.ResourceVersion}}
	obj, err := c.Fake.Invokes(testing.NewRootCreateSubresourceAction(operationsResource, name, "cancel", body), &v1alpha1.Operation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Operation), err
}

func (c *FakeOperations) Retry(ctx context.Context, name string, request *v1alpha1.OperationControlRequest) (result *v1alpha1.Operation, err error) {
	body := &v1alpha1.Operation{ObjectMeta: v1.ObjectMeta{Name: name, UID: request.UID, ResourceVersion: request.ResourceVersion}}
	obj, err := c.Fake.Invokes(testing.NewRootCreateSubresourceAction(operationsResource, name, "retry", body), &v1alpha1.Operation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Operation), err
}
