/*
 *
 *  * Copyright 2021 KubeClipper Authors.
 *  *
 *  * Licensed under the Apache License, Version 2.0 (the "License");
 *  * you may not use this file except in compliance with the License.
 *  * You may obtain a copy of the License at
 *  *
 *  *     http://www.apache.org/licenses/LICENSE-2.0
 *  *
 *  * Unless required by applicable law or agreed to in writing, software
 *  * distributed under the License is distributed on an "AS IS" BASIS,
 *  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  * See the License for the specific language governing permissions and
 *  * limitations under the License.
 *
 */
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"

	scheme "github.com/kubeclipper/kubeclipper/pkg/client/clientset/versioned/scheme"
	v1alpha1 "github.com/kubeclipper/kubeclipper/pkg/scheme/operations/v1alpha1"
)

// OperationTasksGetter has a method to return a OperationTaskInterface.
// A group's client should implement this interface.
type OperationTasksGetter interface {
	OperationTasks() OperationTaskInterface
}

// OperationTaskInterface has methods to work with OperationTask resources.
type OperationTaskInterface interface {
	UpdateStatus(ctx context.Context, operationTask *v1alpha1.OperationTask, opts v1.UpdateOptions) (*v1alpha1.OperationTask, error)
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.OperationTask, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.OperationTaskList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	OperationTaskExpansion
}

// operationTasks implements OperationTaskInterface
type operationTasks struct {
	client rest.Interface
}

// newOperationTasks returns a OperationTasks
func newOperationTasks(c *OperationsV1alpha1Client) *operationTasks {
	return &operationTasks{
		client: c.RESTClient(),
	}
}

// Get takes name of the operationTask, and returns the corresponding operationTask object, and an error if there is any.
func (c *operationTasks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.OperationTask, err error) {
	result = &v1alpha1.OperationTask{}
	err = c.client.Get().
		Resource("operationtasks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of OperationTasks that match those selectors.
func (c *operationTasks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.OperationTaskList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.OperationTaskList{}
	err = c.client.Get().
		Resource("operationtasks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested operationTasks.
func (c *operationTasks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("operationtasks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *operationTasks) UpdateStatus(ctx context.Context, operationTask *v1alpha1.OperationTask, opts v1.UpdateOptions) (result *v1alpha1.OperationTask, err error) {
	result = &v1alpha1.OperationTask{}
	err = c.client.Put().
		Resource("operationtasks").
		Name(operationTask.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(operationTask).
		Do(ctx).
		Into(result)
	return
}
