/*
 *
 *  * Copyright 2021 KubeClipper Authors.
 *  *
 *  * Licensed under the Apache License, Version 2.0 (the "License");
 *  * you may not use this file except in compliance with the License.
 *  * You may obtain a copy of the License at
 *  *
 *  *     http://www.apache.org/licenses/LICENSE-2.0
 *  *
 *  * Unless required by applicable law or agreed to in writing, software
 *  * distributed under the License is distributed on an "AS IS" BASIS,
 *  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  * See the License for the specific language governing permissions and
 *  * limitations under the License.
 *
 */
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	scheme "github.com/kubeclipper/kubeclipper/pkg/client/clientset/versioned/scheme"
	v1alpha1 "github.com/kubeclipper/kubeclipper/pkg/scheme/operations/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// OperationsGetter has a method to return a OperationInterface.
// A group's client should implement this interface.
type OperationsGetter interface {
	Operations() OperationInterface
}

// OperationInterface has methods to work with Operation resources.
type OperationInterface interface {
	Create(ctx context.Context, operation *v1alpha1.Operation, opts v1.CreateOptions) (*v1alpha1.Operation, error)
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Operation, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.OperationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Cancel(ctx context.Context, name string, request *v1alpha1.OperationControlRequest) (*v1alpha1.Operation, error)
	Retry(ctx context.Context, name string, request *v1alpha1.OperationControlRequest) (*v1alpha1.Operation, error)
	OperationExpansion
}

// operations implements OperationInterface
type operations struct {
	client rest.Interface
}

// newOperations returns a Operations
func newOperations(c *OperationsV1alpha1Client) *operations {
	return &operations{
		client: c.RESTClient(),
	}
}

// Get takes name of the operation, and returns the corresponding operation object, and an error if there is any.
func (c *operations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Operation, err error) {
	result = &v1alpha1.Operation{}
	err = c.client.Get().
		Resource("operations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Operations that match those selectors.
func (c *operations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.OperationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.OperationList{}
	err = c.client.Get().
		Resource("operations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested operations.
func (c *operations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("operations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a operation and creates it.  Returns the server's representation of the operation, and an error, if there is any.
func (c *operations) Create(ctx context.Context, operation *v1alpha1.Operation, opts v1.CreateOptions) (result *v1alpha1.Operation, err error) {
	result = &v1alpha1.Operation{}
	err = c.client.Post().
		Resource("operations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(operation).
		Do(ctx).
		Into(result)
	return
}

func (c *operations) Cancel(ctx context.Context, name string, request *v1alpha1.OperationControlRequest) (result *v1alpha1.Operation, err error) {
	body, err := json.Marshal(request)
	if err != nil {
		return nil, fmt.Errorf("encode Operation cancel request: %w", err)
	}
	result = &v1alpha1.Operation{}
	err = c.client.Post().Resource("operations").Name(name).SubResource("cancel").Body(body).Do(ctx).Into(result)
	return
}

func (c *operations) Retry(ctx context.Context, name string, request *v1alpha1.OperationControlRequest) (result *v1alpha1.Operation, err error) {
	body, err := json.Marshal(request)
	if err != nil {
		return nil, fmt.Errorf("encode Operation retry request: %w", err)
	}
	result = &v1alpha1.Operation{}
	err = c.client.Post().Resource("operations").Name(name).SubResource("retry").Body(body).Do(ctx).Into(result)
	return
}
