/*
 *
 *  * Copyright 2021 KubeClipper Authors.
 *  *
 *  * Licensed under the Apache License, Version 2.0 (the "License");
 *  * you may not use this file except in compliance with the License.
 *  * You may obtain a copy of the License at
 *  *
 *  *     http://www.apache.org/licenses/LICENSE-2.0
 *  *
 *  * Unless required by applicable law or agreed to in writing, software
 *  * distributed under the License is distributed on an "AS IS" BASIS,
 *  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  * See the License for the specific language governing permissions and
 *  * limitations under the License.
 *
 */
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/client-go/informers/internalinterfaces"

	"github.com/kubeclipper/kubeclipper/pkg/client/internal"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Operations returns a OperationInformer.
	Operations() OperationInformer
	// OperationTasks returns a OperationTaskInformer.
	OperationTasks() OperationTaskInformer
}

type version struct {
	factory          internal.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internal.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Operations returns a OperationInformer.
func (v *version) Operations() OperationInformer {
	return &operationInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// OperationTasks returns a OperationTaskInformer.
func (v *version) OperationTasks() OperationTaskInformer {
	return &operationTaskInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
