/*
 *
 *  * Copyright 2021 KubeClipper Authors.
 *  *
 *  * Licensed under the Apache License, Version 2.0 (the "License");
 *  * you may not use this file except in compliance with the License.
 *  * You may obtain a copy of the License at
 *  *
 *  *     http://www.apache.org/licenses/LICENSE-2.0
 *  *
 *  * Unless required by applicable law or agreed to in writing, software
 *  * distributed under the License is distributed on an "AS IS" BASIS,
 *  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  * See the License for the specific language governing permissions and
 *  * limitations under the License.
 *
 */
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	clientset "github.com/kubeclipper/kubeclipper/pkg/client/clientset"
	internal "github.com/kubeclipper/kubeclipper/pkg/client/internal"
	v1alpha1 "github.com/kubeclipper/kubeclipper/pkg/client/lister/operations/v1alpha1"
	operationsv1alpha1 "github.com/kubeclipper/kubeclipper/pkg/scheme/operations/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	internalinterfaces "k8s.io/client-go/informers/internalinterfaces"
	cache "k8s.io/client-go/tools/cache"
)

// OperationTaskInformer provides access to a shared informer and lister for
// OperationTasks.
type OperationTaskInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.OperationTaskLister
}

type operationTaskInformer struct {
	factory          internal.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewOperationTaskInformer constructs a new informer for OperationTask type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewOperationTaskInformer(client clientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredOperationTaskInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredOperationTaskInformer constructs a new informer for OperationTask type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredOperationTaskInformer(client clientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OperationsV1alpha1().OperationTasks().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OperationsV1alpha1().OperationTasks().Watch(context.TODO(), options)
			},
		},
		&operationsv1alpha1.OperationTask{},
		resyncPeriod,
		indexers,
	)
}

func (f *operationTaskInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredOperationTaskInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *operationTaskInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&operationsv1alpha1.OperationTask{}, f.defaultInformer)
}

func (f *operationTaskInformer) Lister() v1alpha1.OperationTaskLister {
	return v1alpha1.NewOperationTaskLister(f.Informer().GetIndexer())
}
