# 1.setup go env
# 2.build binary
# 3.upload to oss

name: build-kc

on:
  push:
    branches:
      - 'master'
      - 'release*'

# This ensures that previous jobs for the branch are canceled when the branch is updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: go.mod
      - name: Get tag or branch
        id: extract_branch
        shell: bash
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null)
          branch=${GITHUB_REF#refs/heads/}
          if [[ "$branch" == "master" || "$branch" == "main" ]]; then
            ref_name=$branch
          elif [[ -n "$latest_tag" ]]; then
            ref_name=$latest_tag
          else
            ref_name=$branch
          fi
          echo "The ref name is $ref_name"
          echo "##[set-output name=branch;]${ref_name}"

      - name: Build
        if: github.event_name == 'push'
        run:
          KUBE_BUILD_PLATFORMS="linux/amd64 linux/arm64 darwin/amd64 darwin/arm64" make build

      - name: Compress
        run: |
          pushd dist
          tar -zcvf kc-linux-arm64.tar.gz linux_arm64/
          tar -zcvf kc-linux-amd64.tar.gz kubeclipper-server kubeclipper-agent kubeclipper-proxy kcctl
          tar -zcvf kc-darwin-amd64.tar.gz darwin_amd64/
          tar -zcvf kc-darwin-arm64.tar.gz darwin_arm64/
          popd

      - name: Setup ossutil
        uses: manyuanrong/setup-ossutil@v3.0
        with:
          endpoint:  ${{ secrets.OSS_ENDPOINT }}
          access-key-id: ${{ secrets.OSS_ACCESS_KEY }}
          access-key-secret: ${{ secrets.OSS_ACCESS_SECRET }}
          #sts-token: "sts_token"
      - name: Upload to oss
        run: |
          ossutil cp -rf dist/kc-linux-arm64.tar.gz oss://${{ secrets.OSS_BUCKET }}/kc/${{ steps.extract_branch.outputs.branch }}/
          ossutil cp -rf dist/kc-linux-amd64.tar.gz oss://${{ secrets.OSS_BUCKET }}/kc/${{ steps.extract_branch.outputs.branch }}/
          ossutil cp -rf dist/kc-darwin-amd64.tar.gz oss://${{ secrets.OSS_BUCKET }}/kc/${{ steps.extract_branch.outputs.branch }}/
          ossutil cp -rf dist/kc-darwin-arm64.tar.gz oss://${{ secrets.OSS_BUCKET }}/kc/${{ steps.extract_branch.outputs.branch }}/
