name: go-test-coverage

on: [push, pull_request]

# This ensures that previous jobs for the PR are canceled when the PR is updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Go Test And Coverage
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: go.mod
      - name: Run coverage
        shell: bash
        run: |
          make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5