name: e2e-aio-test

on:
  pull_request:
    branches:
      - 'master'
      - 'release*'

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: [ '1.19' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get branch name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_BASE_REF})"
      - name: Build
        if: github.event_name == 'pull_request'
        run:
          KUBE_BUILD_PLATFORMS="linux/amd64" make build
      - name: deploy
        run: |
          current_branch=${{ steps.extract_branch.outputs.branch }}
          release_version=master
          if [[ "${{ steps.extract_branch.outputs.branch }}" =~ ^release-.* ]]; then
            IFS="-" read -ra items <<< "$(git describe)"
            if [[ ! ${#items[@]} -eq 0 ]]; then
              release_version=${items[0]}
            fi
          fi
          echo current version is ${release_version}
          echo current branch is ${current_branch}
          curl -sfL https://oss.kubeclipper.io/get-kubeclipper.sh | sudo KC_VERSION=${current_branch} KC_REGION=cn bash -
          sudo kcctl deploy --pkg https://oss.kubeclipper.io/release/${release_version}/kc-amd64.tar.gz
      - name: update kc assembly
        run: |
          sudo cp ./dist/kcctl /usr/local/bin/
          sudo systemctl stop kc-agent
          sudo systemctl stop kc-server
          sudo cp ./dist/kubeclipper-agent /usr/local/bin/
          sudo cp ./dist/kubeclipper-server /usr/local/bin/
          sudo systemctl start kc-server
          sudo systemctl start kc-agent
      - name: login and build-e2e
        run: |
          make build-e2e
          ./dist/e2e.test -cluster-install-short-timeout=10m -server-address http://localhost:80 -ginkgo.focus="\[Containerd\]"
          
